### PR TITLE
Solved the migration issue in the order table

### PR DESCRIPTION
**Pull request by wdevmaster**
The code you add solves the problem by running the `php artisan migrate` command in **Laravel 5.8**

### CODE REVIEW

**Comment by fulopattila122** [comment]
Thanks for the PR. This issue is just on my table right now.

The problem is the fact that you're using Laravel 5.8+ doesn't automatically mean your user table has bigInt as id. I have a couple of concrete projects on my radar where:
a.) the project has been started with Laravel 5.7 and has been upgraded to v5.8. `user.id` is still `int`. The package was being added to the project when it was already Laravel 5.8, and just relying on the Laravel version would mislead the migration.
b.) the project has been started on Laravel 5.8, but as a very first step, the default Laravel migration has been modified back to using `int` for `user.id`. Again, the Laravel version is not sufficient to tell whether the user table's id field is `int` or `bigInt`

See:
https://konekt.dev/user/1.1/installation#laravel-58-and-bigint-compatibility
artkonekt/user#1
vanilophp/framework#42

I'm about to introduce a generic solution that could be used across packages.

**Comment by fulopattila122** [comment]
Also, see discussion at the [Laravel commit](https://github.com/laravel/laravel/commit/426df7a0e4d489439002cf99c37246aeebdc5327). Quite a pain in the ass if you ask me :)

**Comment by wdevmaster** [comment]
Ok, well, thanks for the effort, this project is excellent and, well, you know that the project could be added to a system of taxes and fees that systems of this style always have, and again, thanks for the effort.

**Comment by fulopattila122** [comment]
The tax calculation module is scheduled for v1.2.

To solve the migration problem I've been working on this package for the last 2 days: https://github.com/artkonekt/laravel-migration-compatibility

The [current concept](https://github.com/artkonekt/laravel-migration-compatibility/blob/f475ca48d948c10e453dbaf218a8c7c782f1a742/README.md) is to extend `Blueprint` with a mechanism that can detect the field type from the related field:

```php
Schema::create('profiles', function (Blueprint $table) {
    $table->increments('id');

    // Make `user_id` field the same type as the `id` field of the `user` table:
    $table->intOrBigIntBasedOnRelated('user_id', Schema::connection(null), 'users.id');

    //...

    $table->foreign('user_id')
        ->references('id')
        ->on('users');
});
```

Unfortunately it doesn't seem to be viable, because of several reasons:
- The Blueprint is DB engine agnostic and is only intended to have access to the DB connection while it's building the SQL to apply,
- The Blueprint definition (the migration file itself) happens before that,
- The SQL from the to-be-applied blueprints get generated at once and at the time of the generation the user table might not even be present in the Database (think of the very first run of a migration).

Therefore I will likely make a pivot and make a common configuration that packages can use to read the intended type from.

**Comment by fulopattila122** [comment]
Fix is coming today!

**Comment by upeksha1996** [comment]
Hi, Is this issue s fixed now?

**Comment by fulopattila122** [comment]
Yes, it's been fixed now on master. It'll be released with v1.0.0, until then you can use `1.0@dev` tag.

**Comment by fulopattila122** [comment]
Backported for v0.5 as well, exact version is `0.5.2` that contains the fix.

**Pull request closed without merging**
